version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  postgrest:
    image: postgrest/postgrest:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf
    command: ["postgrest", "/etc/postgrest.conf"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - postgrest
    ports:
      - "8080:80"

volumes:
  pgdata:
